name: Prettier Write

on:
  # use Push if you want to trigger the workflow on every push to the repository in the main branch
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

  # Lint and format code with Prettier, ESLint and Stylelint
  lint-and-format:
    runs-on: ubuntu-latest
    needs: [setup-node]
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: |
          yarn install
          yarn prettier --write .
