name: Main Branch Linting, Testing, and SonarQube Scan

on:
  pull_request:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

  lint-and-format:
    runs-on: ubuntu-latest
    needs: [setup-node]
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Check for changes with Prettier
        id: prettier-check
        run: |
          yarn prettier --check **/*.js **/*.jsx **/*.css

      - name: Format code with Prettier
        if: steps.prettier-check.outcome == 'failure'
        run: |
          yarn prettier --write **/*.js **/*.jsx **/*.css
          git config --local user.email ${{ github.actor }}@users.noreply.github.com
          git config --local user.name ${{ github.actor }}
          git add .
          git commit -m "Automatic code formatting with Prettier"
          git push origin ${{env.BRANCH_NAME}}-prettier-formatting

      - name: Create pull request
        if: steps.prettier-check.outcome == 'failure'
        run: |
          gh pr create --title "Format code with Prettier" --body "This PR is auto-generated by GitHub Actions" --base "${{ github.base_ref }}" --head ${{env.BRANCH_NAME}}-prettier-formatting --repo ${{ github.repository }}
