name: Main Branch Linting ,Testing and SonarQube Scan

on:
  # use Push if you want to trigger the workflow on every push to the repository in the main branch
  pull_request:
  # use workflow_dispatch if you want to trigger the workflow manually
  workflow_dispatch:

env:
  # Name Branch as per you working on
  BRANCH_NAME: ${{ github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

  # Lint and format code with Prettier, ESLint and Stylelint
  lint-and-format:
    runs-on: ubuntu-latest
    needs: [setup-node]
    steps:

      - name: Checkout code repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          yarn install
          yarn add prettier gh 

      # Check for changes with Prettier
      - name: Check for changes with Prettier
        id: prettier-check
        run: |
          if yarn prettier --check **/*.js **/*.jsx **/*.css ; then
            echo "PRETTIER_CHECK_RESULT=success" >> $GITHUB_ENV
          else
            echo "PRETTIER_CHECK_RESULT=failure" >> $GITHUB_ENV
          fi

      - name: Format code with Prettier
        if: steps.prettier-check.outcome == 'failure'
        run: |
          yarn prettier --write **/*.js **/*.jsx **/*.css
          git config --local user.email ${{ github.actor }}@users.noreply.github.com
          git config --local user.name ${{ github.actor }}
          git add .
          git commit -m "Automatic code formatting with Prettier"
          git push origin ${{env.BRANCH_NAME}}-prettier-formatting

      - name: Create pull request
        if: steps.prettier-check.outcome == 'failure'
        run: |
          gh pr create --title "Format code with Prettier" --body "This PR is auto-generated by GitHub Actions" --base "${{ github.base_ref }}" --head ${{env.BRANCH_NAME}}-prettier-formatting --repo ${{ github.repository }}
