name: Main Branch Linting ,Testing and SonarQube Scan

on:
  # use Push if you want to trigger the workflow on every push to the repository in the main branch
  pull_request:
  # use workflow_dispatch if you want to trigger the workflow manually
  workflow_dispatch:

env:
  # Name Branch as per you working on
  BRANCH_NAME: ${{ github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

  # Lint and format code with Prettier, ESLint and Stylelint
  lint-and-format:
    runs-on: ubuntu-latest
    needs: [setup-node]
    steps:

      - name: Checkout code repository
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          yarn install
          yarn add prettier gh 
          yarn prettier --write **/*.js **/*.jsx **/*.css
